name: url-shortener-aadit
region: blr

databases:
  - name: url-shortener-aadit-storage
    engine: PG
    version: "18"
    production: true
    cluster_name: db-url-shortner
    db_name: urlshortener_aadit
    db_user: urlshortener_aadit

services:
  - name: api
    github:
      repo: aaditagarwal/DigitalOcean_URL_Shortener
      branch: main
      deploy_on_push: false
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
    envs:
      - key: PORT
        scope: RUN_TIME
        value: "8080"
      - key: JAVA_OPTS
        scope: RUN_TIME
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
      - key: PUBLIC_BASE_URL
        scope: RUN_TIME
        value: ${APP_URL}
      - key: SPRING_DATASOURCE_URL
        scope: RUN_TIME
        value: ${url-shortener-aadit-storage.JDBC_DATABASE_URL}
      - key: SPRING_DATASOURCE_USERNAME
        scope: RUN_TIME
        value: ${url-shortener-aadit-storage.USERNAME}
      - key: SPRING_DATASOURCE_PASSWORD
        scope: RUN_TIME
        type: SECRET
        value: ${url-shortener-aadit-storage.PASSWORD}
