-- short_urls: core persistence for the URL shortener (soft-delete via active flag)
CREATE TABLE short_urls (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(16)  NOT NULL,
    original_url VARCHAR(2048) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at   TIMESTAMP WITH TIME ZONE NULL,
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    click_count  BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_short_urls_code UNIQUE (code)
);

CREATE INDEX idx_short_urls_active_expires ON short_urls (active, expires_at);
