package com.digitalocean.urlshortener;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.digitalocean.urlshortener.persistence.ShortUrlRepository;
import com.digitalocean.urlshortener.service.CodeGenerator;
import com.digitalocean.urlshortener.service.CustomCodeConflictException;
import com.digitalocean.urlshortener.service.ReservedCodeChecker;
import com.digitalocean.urlshortener.service.ReservedCodeException;
import com.digitalocean.urlshortener.service.UrlNotFoundException;
import com.digitalocean.urlshortener.service.UrlShortenerService;
import com.digitalocean.urlshortener.support.InMemoryShortUrlRepository;
import com.digitalocean.urlshortener.web.dto.CreateUrlRequest;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

/**
 * Functional-requirement coverage without JDBC/H2/Flyway — service + in-memory repository double.
 *
 * <ol>
 *   <li>Create (auto or custom) returns full short URL + metadata
 *   <li>Metadata GET vs redirect resolve (click counter)
 *   <li>Delete soft-inactivates the short URL
 * </ol>
 */
class UrlShortenerFunctionalRequirementsTest {

  private static final String BASE = "http://localhost:8080";

  private ShortUrlRepository repository;
  private CodeGenerator codeGenerator;
  private UrlShortenerService service;

  @BeforeEach
  void setUp() {
    repository = InMemoryShortUrlRepository.create();
    codeGenerator = mock(CodeGenerator.class);
    service = new UrlShortenerService(repository, codeGenerator, new ReservedCodeChecker());
  }

  @Nested
  @DisplayName("1. Create short URL")
  class CreateRequirement {

    @Test
    @DisplayName("Happy: long URL → unique generated short URL + full metadata")
    void createAutoGeneratedReturnsFullShortUrlAndMetadata() {
      when(codeGenerator.generate()).thenReturn("Ab12Cd34");

      var response =
          service.create(
              new CreateUrlRequest("https://example.com/very/long/path?q=1", null), BASE);

      assertThat(response.code()).isEqualTo("Ab12Cd34");
      assertThat(response.shortUrl()).isEqualTo(BASE + "/Ab12Cd34");
      assertThat(response.originalUrl()).isEqualTo("https://example.com/very/long/path?q=1");
      assertThat(response.createdAt()).isNotNull();
      assertThat(response.active()).isTrue();
      assertThat(response.clickCount()).isZero();
      assertThat(repository.findByCode("Ab12Cd34")).isPresent();
    }

    @Test
    @DisplayName("Happy: customCode → exact short URL + metadata")
    void createCustomCodeReturnsExactShortUrlAndMetadata() {
      var response =
          service.create(
              new CreateUrlRequest("https://example.com/launch", null, "product-launch"), BASE);

      assertThat(response.code()).isEqualTo("product-launch");
      assertThat(response.shortUrl()).isEqualTo(BASE + "/product-launch");
      assertThat(response.originalUrl()).isEqualTo("https://example.com/launch");
      assertThat(response.active()).isTrue();
      assertThat(response.clickCount()).isZero();
    }

    @Test
    @DisplayName("Failure: duplicate customCode → conflict")
    void createFailsWhenCustomCodeTaken() {
      service.create(new CreateUrlRequest("https://example.com/a", null, "unique-slot"), BASE);

      assertThatThrownBy(
              () ->
                  service.create(
                      new CreateUrlRequest("https://example.com/b", null, "unique-slot"), BASE))
          .isInstanceOf(CustomCodeConflictException.class);
    }

    @Test
    @DisplayName("Failure: reserved customCode")
    void createFailsForReservedCustomCode() {
      assertThatThrownBy(
              () ->
                  service.create(
                      new CreateUrlRequest("https://example.com", null, "api"), BASE))
          .isInstanceOf(ReservedCodeException.class);
    }
  }

  @Nested
  @DisplayName("2. Get metadata + redirect")
  class GetRequirement {

    @Test
    @DisplayName("Happy: metadata does not increment clicks; redirect does")
    void metadataAndRedirectMaintainClickCounter() {
      service.create(
          new CreateUrlRequest("https://example.com/destination", null, "click-demo"), BASE);

      var meta = service.getMetadata("click-demo", BASE);
      assertThat(meta.clickCount()).isZero();
      assertThat(meta.originalUrl()).isEqualTo("https://example.com/destination");

      assertThat(service.resolveForRedirect("click-demo"))
          .isEqualTo("https://example.com/destination");
      assertThat(repository.findByCode("click-demo").orElseThrow().getClickCount()).isEqualTo(1L);

      assertThat(service.getMetadata("click-demo", BASE).clickCount()).isEqualTo(1L);

      service.resolveForRedirect("click-demo");
      assertThat(repository.findByCode("click-demo").orElseThrow().getClickCount()).isEqualTo(2L);
    }

    @Test
    @DisplayName("Failure: metadata missing → not found")
    void metadataFailurePaths() {
      assertThatThrownBy(() -> service.getMetadata("nosuch99", BASE))
          .isInstanceOf(UrlNotFoundException.class);
    }

    @Test
    @DisplayName("Failure: redirect missing → not found")
    void redirectFailurePaths() {
      assertThatThrownBy(() -> service.resolveForRedirect("nosuch99"))
          .isInstanceOf(UrlNotFoundException.class);
    }
  }

  @Nested
  @DisplayName("3. Delete (soft-inactivate)")
  class DeleteRequirement {

    @Test
    @DisplayName("Happy: delete inactivates; metadata + redirect then not found; second delete ok")
    void deleteInactivatesAndBlocksReads() {
      service.create(
          new CreateUrlRequest("https://example.com/remove-me", null, "to-remove"), BASE);

      service.delete("to-remove");
      assertThat(repository.findByCode("to-remove").orElseThrow().isActive()).isFalse();

      assertThatThrownBy(() -> service.getMetadata("to-remove", BASE))
          .isInstanceOf(UrlNotFoundException.class);
      assertThatThrownBy(() -> service.resolveForRedirect("to-remove"))
          .isInstanceOf(UrlNotFoundException.class);

      service.delete("to-remove"); // idempotent
    }

    @Test
    @DisplayName("Failure: delete missing → not found")
    void deleteFailurePaths() {
      assertThatThrownBy(() -> service.delete("nosuch99")).isInstanceOf(UrlNotFoundException.class);
    }
  }

  @Nested
  @DisplayName("Full lifecycle")
  class FullLifecycle {

    @Test
    @DisplayName("create → metadata → redirect (clicks) → delete → blocked reads")
    void endToEndLifecycle() {
      var created =
          service.create(
              new CreateUrlRequest("https://example.com/lifecycle", null, "life-cycle"), BASE);
      assertThat(created.shortUrl()).isEqualTo(BASE + "/life-cycle");

      assertThat(service.getMetadata("life-cycle", BASE).clickCount()).isZero();
      assertThat(service.resolveForRedirect("life-cycle"))
          .isEqualTo("https://example.com/lifecycle");
      assertThat(service.getMetadata("life-cycle", BASE).clickCount()).isEqualTo(1L);

      service.delete("life-cycle");
      assertThatThrownBy(() -> service.getMetadata("life-cycle", BASE))
          .isInstanceOf(UrlNotFoundException.class);
      assertThatThrownBy(() -> service.resolveForRedirect("life-cycle"))
          .isInstanceOf(UrlNotFoundException.class);
    }
  }
}
