package com.digitalocean.urlshortener;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.matchesPattern;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.header;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.digitalocean.urlshortener.persistence.ShortUrlRepository;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

/**
 * End-to-end validation of the product functional requirements:
 *
 * <ol>
 *   <li>Create (auto or custom) returns full short URL + metadata
 *   <li>Metadata GET vs redirect GET (click counter)
 *   <li>Delete soft-inactivates the short URL
 * </ol>
 */
@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
class UrlShortenerFunctionalRequirementsTest {

  @Autowired private MockMvc mockMvc;
  @Autowired private ObjectMapper objectMapper;
  @Autowired private ShortUrlRepository repository;

  @Nested
  @DisplayName("1. Create short URL")
  class CreateRequirement {

    @Test
    @DisplayName("Happy: long URL → unique generated short URL + full metadata")
    void createAutoGeneratedReturnsFullShortUrlAndMetadata() throws Exception {
      MvcResult result =
          mockMvc
              .perform(
                  post("/api/v1/urls")
                      .contentType(MediaType.APPLICATION_JSON)
                      .content(
                          "{\"url\":\"https://example.com/very/long/path?q=1\",\"expiresAt\":null}"))
              .andExpect(status().isCreated())
              .andExpect(header().string("Location", matchesPattern("/api/v1/urls/[A-Za-z0-9]{8}")))
              .andExpect(jsonPath("$.code").value(matchesPattern("[A-Za-z0-9]{8}")))
              .andExpect(jsonPath("$.shortUrl").value(matchesPattern("^http://localhost:8080/[A-Za-z0-9]{8}$")))
              .andExpect(jsonPath("$.originalUrl").value("https://example.com/very/long/path?q=1"))
              .andExpect(jsonPath("$.createdAt").exists())
              .andExpect(jsonPath("$.active").value(true))
              .andExpect(jsonPath("$.clickCount").value(0))
              .andReturn();

      JsonNode body = objectMapper.readTree(result.getResponse().getContentAsString());
      assertThat(body.get("shortUrl").asText()).endsWith("/" + body.get("code").asText());
      assertThat(repository.findByCode(body.get("code").asText())).isPresent();
    }

    @Test
    @DisplayName("Happy: customCode → exact short URL + metadata")
    void createCustomCodeReturnsExactShortUrlAndMetadata() throws Exception {
      mockMvc
          .perform(
              post("/api/v1/urls")
                  .contentType(MediaType.APPLICATION_JSON)
                  .content(
                      "{\"url\":\"https://example.com/launch\",\"customCode\":\"product-launch\"}"))
          .andExpect(status().isCreated())
          .andExpect(header().string("Location", "/api/v1/urls/product-launch"))
          .andExpect(jsonPath("$.code").value("product-launch"))
          .andExpect(jsonPath("$.shortUrl").value("http://localhost:8080/product-launch"))
          .andExpect(jsonPath("$.originalUrl").value("https://example.com/launch"))
          .andExpect(jsonPath("$.active").value(true))
          .andExpect(jsonPath("$.clickCount").value(0));
    }

    @Test
    @DisplayName("Failure: missing url → 400")
    void createFailsWithoutUrl() throws Exception {
      mockMvc
          .perform(post("/api/v1/urls").contentType(MediaType.APPLICATION_JSON).content("{}"))
          .andExpect(status().isBadRequest())
          .andExpect(jsonPath("$.fieldErrors[?(@.field=='url')]").exists());
    }

    @Test
    @DisplayName("Failure: non-http url → 400")
    void createFailsForNonHttpUrl() throws Exception {
      mockMvc
          .perform(
              post("/api/v1/urls")
                  .contentType(MediaType.APPLICATION_JSON)
                  .content("{\"url\":\"ftp://example.com/file\"}"))
          .andExpect(status().isBadRequest());
    }

    @Test
    @DisplayName("Failure: duplicate customCode → 409")
    void createFailsWhenCustomCodeTaken() throws Exception {
      String payload =
          "{\"url\":\"https://example.com/a\",\"customCode\":\"unique-slot\"}";
      mockMvc
          .perform(post("/api/v1/urls").contentType(MediaType.APPLICATION_JSON).content(payload))
          .andExpect(status().isCreated());
      mockMvc
          .perform(
              post("/api/v1/urls")
                  .contentType(MediaType.APPLICATION_JSON)
                  .content("{\"url\":\"https://example.com/b\",\"customCode\":\"unique-slot\"}"))
          .andExpect(status().isConflict());
    }

    @Test
    @DisplayName("Failure: reserved customCode → 400")
    void createFailsForReservedCustomCode() throws Exception {
      mockMvc
          .perform(
              post("/api/v1/urls")
                  .contentType(MediaType.APPLICATION_JSON)
                  .content("{\"url\":\"https://example.com\",\"customCode\":\"api\"}"))
          .andExpect(status().isBadRequest());
    }
  }

  @Nested
  @DisplayName("2. Get metadata + redirect")
  class GetRequirement {

    @Test
    @DisplayName("Happy: metadata returns fields without incrementing clicks; redirect increments")
    void metadataAndRedirectMaintainClickCounter() throws Exception {
      String code = create("https://example.com/destination", "click-demo");

      mockMvc
          .perform(get("/api/v1/urls/" + code))
          .andExpect(status().isOk())
          .andExpect(jsonPath("$.code").value(code))
          .andExpect(jsonPath("$.shortUrl").value("http://localhost:8080/" + code))
          .andExpect(jsonPath("$.originalUrl").value("https://example.com/destination"))
          .andExpect(jsonPath("$.active").value(true))
          .andExpect(jsonPath("$.clickCount").value(0));

      mockMvc
          .perform(get("/" + code))
          .andExpect(status().isFound())
          .andExpect(header().string("Location", "https://example.com/destination"));

      assertThat(repository.findByCode(code).orElseThrow().getClickCount()).isEqualTo(1L);

      mockMvc
          .perform(get("/api/v1/urls/" + code))
          .andExpect(status().isOk())
          .andExpect(jsonPath("$.clickCount").value(1));

      mockMvc.perform(get("/" + code)).andExpect(status().isFound());
      assertThat(repository.findByCode(code).orElseThrow().getClickCount()).isEqualTo(2L);
    }

    @Test
    @DisplayName("Failure: metadata missing → 404; invalid code → 400")
    void metadataFailurePaths() throws Exception {
      mockMvc.perform(get("/api/v1/urls/nosuch99")).andExpect(status().isNotFound());
      mockMvc.perform(get("/api/v1/urls/xy")).andExpect(status().isBadRequest());
    }

    @Test
    @DisplayName("Failure: redirect missing / invalid → 404")
    void redirectFailurePaths() throws Exception {
      mockMvc.perform(get("/nosuch99")).andExpect(status().isNotFound());
      mockMvc.perform(get("/xy")).andExpect(status().isNotFound());
    }
  }

  @Nested
  @DisplayName("3. Delete (soft-inactivate)")
  class DeleteRequirement {

    @Test
    @DisplayName("Happy: delete inactivates; metadata + redirect then 404; second delete 204")
    void deleteInactivatesAndBlocksReads() throws Exception {
      String code = create("https://example.com/remove-me", "to-remove");

      mockMvc.perform(delete("/api/v1/urls/" + code)).andExpect(status().isNoContent());
      assertThat(repository.findByCode(code).orElseThrow().isActive()).isFalse();

      mockMvc.perform(get("/api/v1/urls/" + code)).andExpect(status().isNotFound());
      mockMvc.perform(get("/" + code)).andExpect(status().isNotFound());

      mockMvc.perform(delete("/api/v1/urls/" + code)).andExpect(status().isNoContent());
    }

    @Test
    @DisplayName("Failure: delete missing → 404; invalid code → 400")
    void deleteFailurePaths() throws Exception {
      mockMvc.perform(delete("/api/v1/urls/nosuch99")).andExpect(status().isNotFound());
      mockMvc.perform(delete("/api/v1/urls/xy")).andExpect(status().isBadRequest());
    }
  }

  @Nested
  @DisplayName("Full lifecycle")
  class FullLifecycle {

    @Test
    @DisplayName("create → metadata → redirect (clicks) → delete → blocked reads")
    void endToEndLifecycle() throws Exception {
      // 1. Create
      MvcResult created =
          mockMvc
              .perform(
                  post("/api/v1/urls")
                      .contentType(MediaType.APPLICATION_JSON)
                      .content(
                          "{\"url\":\"https://example.com/lifecycle\",\"customCode\":\"life-cycle\"}"))
              .andExpect(status().isCreated())
              .andExpect(jsonPath("$.shortUrl").value("http://localhost:8080/life-cycle"))
              .andReturn();
      String code =
          objectMapper.readTree(created.getResponse().getContentAsString()).get("code").asText();

      // 2. Metadata (no click) + redirect (click)
      mockMvc
          .perform(get("/api/v1/urls/" + code))
          .andExpect(status().isOk())
          .andExpect(jsonPath("$.clickCount").value(0));
      mockMvc
          .perform(get("/" + code))
          .andExpect(status().isFound())
          .andExpect(header().string("Location", "https://example.com/lifecycle"));
      mockMvc
          .perform(get("/api/v1/urls/" + code))
          .andExpect(jsonPath("$.clickCount").value(1));

      // 3. Delete
      mockMvc.perform(delete("/api/v1/urls/" + code)).andExpect(status().isNoContent());
      mockMvc.perform(get("/api/v1/urls/" + code)).andExpect(status().isNotFound());
      mockMvc.perform(get("/" + code)).andExpect(status().isNotFound());
    }
  }

  private String create(String url, String customCode) throws Exception {
    MvcResult result =
        mockMvc
            .perform(
                post("/api/v1/urls")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content(
                        "{\"url\":\"%s\",\"customCode\":\"%s\"}".formatted(url, customCode)))
            .andExpect(status().isCreated())
            .andReturn();
    return objectMapper.readTree(result.getResponse().getContentAsString()).get("code").asText();
  }
}
